[workspace]
resolver = "2"

members = [
    "crates/*"
]

[workspace.dependencies]
osp_protocol = { version = "=0.0.1", path = "crates/protocol" }
osp_server_sdk = { version = "=0.0.1", path = "crates/server" }
osp_client_sdk = { version = "=0.0.1", path = "crates/client" }